import Navbar from "@/components/Navbar";
import "./globals.css";

import { Lexend } from "next/font/google";
const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "HRM",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
