import Navbar from "@/components/Navbar";
import "./globals.css";

import { Lexend } from "next/font/google";
import Sidebar from "@/components/Sidebar";
const lexend = Lexend({ subsets: ["latin"] });

export const metadata = {
  title: "HRM",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexend.className} antialiased px-12 py-4 `}>
        <Navbar />
        <div className="flex gap-4 mt-5">
          <Sidebar />
          <div className="flex-1">{children}</div>
        </div>
      </body>
    </html>
  );
}
