// Sunucu tarafı işlemleri
export const metadata = {
  title: "HRM",
  // description: "Generated by create next app",
};

import RootLayout from "@/components/RootLayout"; // İstemci tarafı layout component'ini burada kullanıyoruz.

export default function Layout({ children }) {
  return <RootLayout>{children}</RootLayout>;
}
